services:
  - type: web
    name: qrmenu-api
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qrmenu-db
          property: connectionString
      - key: FIREBASE_PROJECT_ID
        sync: false

cronjobs:
  - name: db-dump
    schedule: "0 3 * * *"
    command: "./scripts/db_dump.sh" 